/*
 * spi_pio.c — PIO-based SPI implementation for CryptoLite-ICE
 * controlpaths.com | lut7.dev
 */

#include "spi_pio.h"
#include "spi_pio.pio.h"   // generated by CMake from spi_pio.pio
#include "pins.h"
#include "hardware/pio.h"
#include "pico/time.h"

static uint _pio_offset;
static bool _pio_loaded = false;

void spi_pio_init(void) {
    if (!_pio_loaded) {
        _pio_offset = pio_add_program(SPI_PIO_BLOCK, &spi_pio_program);
        _pio_loaded = true;
    }
    spi_pio_program_init(
        SPI_PIO_BLOCK,
        SPI_PIO_SM,
        _pio_offset,
        PIN_ICE_SO,   // MOSI → Flash DI  (RP2040 output, GPIO11)
        PIN_ICE_SI,   // MISO ← Flash DO  (RP2040 input,  GPIO8)
        PIN_ICE_SCK,  // SCK
        SPI_PIO_FREQ_HZ
    );
}

// ── Helpers ───────────────────────────────────────────────────────────────

/* PIO byte transfer with safety timeout. The PIO state machine should
 * always drain the TX FIFO and refill the RX FIFO at SPI_PIO_FREQ_HZ
 * (1 byte ~= 8 µs at 1 MHz), so anything beyond a few ms means the SM
 * has stalled — typically because the FPGA / flash bus state was changed
 * out from under it. Returning instead of spinning forever keeps the USB
 * dispatcher responsive so we can recover by re-attaching. */
#define PIO_BYTE_TIMEOUT_US  5000u

static inline bool _pio_put_byte(uint8_t byte) {
    uint32_t t0 = time_us_32();
    while (pio_sm_is_tx_fifo_full(SPI_PIO_BLOCK, SPI_PIO_SM)) {
        if ((uint32_t)(time_us_32() - t0) > PIO_BYTE_TIMEOUT_US) return false;
        tight_loop_contents();
    }
    pio_sm_put(SPI_PIO_BLOCK, SPI_PIO_SM, (uint32_t)byte << 24);
    return true;
}

static inline bool _pio_get_byte(uint8_t *out) {
    uint32_t t0 = time_us_32();
    while (pio_sm_is_rx_fifo_empty(SPI_PIO_BLOCK, SPI_PIO_SM)) {
        if ((uint32_t)(time_us_32() - t0) > PIO_BYTE_TIMEOUT_US) return false;
        tight_loop_contents();
    }
    *out = (uint8_t)pio_sm_get(SPI_PIO_BLOCK, SPI_PIO_SM);
    return true;
}

// ── Public API ────────────────────────────────────────────────────────────

void spi_pio_write(const uint8_t *src, size_t len) {
    uint8_t scratch;
    for (size_t i = 0; i < len; i++) {
        if (!_pio_put_byte(src[i])) return;
        if (!_pio_get_byte(&scratch)) return;
    }
}

void spi_pio_read(uint8_t *dst, size_t len) {
    for (size_t i = 0; i < len; i++) {
        if (!_pio_put_byte(0x00)) {
            for (size_t j = i; j < len; j++) dst[j] = 0;
            return;
        }
        if (!_pio_get_byte(&dst[i])) {
            for (size_t j = i + 1; j < len; j++) dst[j] = 0;
            return;
        }
    }
}

void spi_pio_write_read(const uint8_t *src, uint8_t *dst, size_t len) {
    for (size_t i = 0; i < len; i++) {
        if (!_pio_put_byte(src[i])) {
            for (size_t j = i; j < len; j++) dst[j] = 0;
            return;
        }
        if (!_pio_get_byte(&dst[i])) {
            for (size_t j = i + 1; j < len; j++) dst[j] = 0;
            return;
        }
    }
}
